version: '3.9'

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - question-service
      - submit-service
    environment:
      - USER_SERVICE_URL=http://user-service:5001
      - QUESTION_SERVICE_URL=http://question-service:5002
      - SUBMIT_SERVICE_URL=http://submit-service:5003
    networks:
      - codepit-net

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    environment:
      - NEXT_PUBLIC_API_URL=http://gateway:8080
    networks:
      - codepit-net

  user-service:
    image: pg878/user-service:latest
    container_name: user-service
    ports:
      - "5001:5001"
    networks:
      - codepit-net

  question-service:
    image: pg878/question-service:latest
    container_name: question-service
    ports:
      - "5002:5002"
    networks:
      - codepit-net

  submit-service:
    image: pg878/submit-service:latest
    container_name: submit-service
    ports:
      - "5003:5003"
    networks:
      - codepit-net

networks:
  codepit-net:
    driver: bridge