version: '3.9'

services:
  api-gateway:
    build: ./gateway-js
    container_name: api-gateway
    ports:
      - "3001:3001"
    env_file:
      - ./gateway-js/.env
    depends_on:
      - user-service
      - problem-service

  user-service:
    image: pg878/user-service:latest
    container_name: user-service
    ports:
      - "8080:8080"
    env_file:
      - .env.user

  problem-service:
    image: pg878/problem-service:latest
    container_name: problem-service
    ports:
      - "8083:8083"
    env_file:
      - .env.problem

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - api-gateway